version: '3.9'
services:
  mongodb:
    image: mongo:7
    ports:
      - 27017:27017

  repository:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REP_PUB_KEY: credential_file
      REP_ADDRESS: "0.0.0.0:5000"
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
